on: push

name: Test

jobs:
  build_lin:
    name: Ubuntu test
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Ubuntu tools
        run: |
          sudo apt update
          sudo apt-get install -y libboost-dev libboost-system-dev libboost-date-time-dev libsodium-dev
      - name: Checkout code
        uses: actions/checkout@master
      - name: Test
        run: |
          npm install
          ./tests/run.sh